name: deployment workflow development directory
  on:[push]
  jobs:

  build:
    name: deployment
    runs-on: ubuntu-latest
    steps:
    - name: 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME_HOST }}
        key: ${{ secrets.KEY_HOST }}
        port: ${{ secrets.PORT_HOST }}
        script: |
            cd /var/www/imlchile.cl/rentacar_test/
            git pull
            exit